name: vkonnect
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  eva_icons_flutter: ^2.0.1
  firebase_auth: ^0.18.4+1
  firebase_core: ^0.5.3
  font_awesome_flutter: ^8.11.0
  google_sign_in: ^4.5.6
  page_transition: ^1.1.7+5
  provider: ^4.3.2+1
  firebase_storage: ^5.2.0
  image_picker: ^0.6.7+17

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/login.png
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins.ttf

    - family: Monteserrat
      fonts:
        - asset: assets/fonts/Monteserrat.ttf

